exec-once = /usr/lib/pam_kwallet_init & kwalletd6
exec-once = hyprctl setcursor catppuccin-mocha-blue-cursors 28
exec-once = hyprpm reload -n
exec-once = ibus start --type wayland
#exec-once = hyprpaper & swaync
#exec-once = dms run
