source = $HOME/.config/hypr/mocha.conf

$accent = $sapphire
$accentAlpha = $sapphireAlpha

background {
    monitor =
    path = ~/.config/backgrounds/Clearnight.jpg
    color = $base
    blur_passes = 2
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = $surface0

    outer_color = $accent
    check_color=$accent
    fail_color=$red
    capslock_color=$yellow

    font_color = $text
    fade_on_empty = false
    rounding = 15

    position = 0, -20
    halign = center
    valign = center
}
