source = $HOME/.config/hypr/mocha.conf

$accent = $sapphire
$accentAlpha = $sapphireAlpha
$font = 0xProto Nerd Font

background {
    monitor =
    path = ~/.config/backgrounds/Clearnight.jpg
    color = $base
    blur_passes = 2
}

# TIME
label {
  monitor =
  text = $TIME
  color = $text
  font_size = 72
  font_family = $font
  position = -30, 0
  halign = right
  valign = top
}

# DATE
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $text
  font_size = 20
  font_family = $font
  position = -30, -130
  halign = right
  valign = top
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = $surface0

    outer_color = $accent
    check_color=$accent
    fail_color=$red
    capslock_color=$yellow

    font_color = $text
    fade_on_empty = false
    rounding = 15

    position = 0, -20
    halign = center
    valign = center
}
